import Card from './card';
export const CARDS = [
  new Card(
    '1',
    'Suki McClunaghan',
    'Suki',
    'McClunaghan',
    'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    'https://picsum.photos/200',
    'Honorable',
    false,
  ),
  new Card(
    '2',
    'Sheridan Pleming',
    'Sheridan',
    'Pleming',
    'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    'https://picsum.photos/200',
    'Ms',
    false,
  ),
  new Card(
    3,
    'Dorie Halbert',
    'Dorie',
    'Halbert',
    'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    'https://picsum.photos/200',
    'Mr',
    true,
  ),
  new Card(
    4,
    'Ethan Parell',
    'Ethan',
    'Parell',
    'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    'https://picsum.photos/200',
    'Mr',
    true,
  ),
  new Card(
    5,
    'Coleen Martignon',
    'Coleen',
    'Martignon',
    'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    'https://picsum.photos/200',
    'Ms',
    false,
  ),
  new Card(
    6,
    'Frederick Barfford',
    'Frederick',
    'Barfford',
    'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    'https://picsum.photos/200',
    'Dr',
    false,
  ),
  new Card(
    7,
    'Clementius Grunnell',
    'Clementius',
    'Grunnell',
    'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    'https://picsum.photos/200',
    'Mrs',
    false,
  ),
  new Card(
    8,
    'Alonso Duckerin',
    'Alonso',
    'Duckerin',
    'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    'https://picsum.photos/200',
    'Honorable',
    false,
  ),
  new Card(
    9,
    'Gladys Hurndall',
    'Gladys',
    'Hurndall',
    'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    'https://picsum.photos/200',
    'Ms',
    true,
  ),
  new Card(
    10,
    'Guglielmo Chaney',
    'Guglielmo',
    'Chaney',
    'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    'https://picsum.photos/200',
    'Mrs',
    false,
  ),
  new Card(
    11,
    'Stevie Duchatel',
    'Stevie',
    'Duchatel',
    'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    'https://picsum.photos/200',
    'Mrs',
    false,
  ),
  new Card(
    12,
    'Koenraad Daddow',
    'Koenraad',
    'Daddow',
    'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    'https://picsum.photos/200',
    'Mr',
    false,
  ),
  new Card(
    13,
    'Ellyn Cosh',
    'Ellyn',
    'Cosh',
    'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    'https://picsum.photos/200',
    'Rev',
    true,
  ),
  new Card(
    14,
    'Ashbey Kirsche',
    'Ashbey',
    'Kirsche',
    'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    'https://picsum.photos/200',
    'Rev',
    false,
  ),
  new Card(
    15,
    'Libby Gartin',
    'Libby',
    'Gartin',
    'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    'https://picsum.photos/200',
    'Honorable',
    true,
  ),
  new Card(
    16,
    'Reinhard Pywell',
    'Reinhard',
    'Pywell',
    'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    'https://picsum.photos/200',
    'Dr',
    false,
  ),
  new Card(
    17,
    'Bette Vernazza',
    'Bette',
    'Vernazza',
    'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    'https://picsum.photos/200',
    'Mrs',
    false,
  ),
  new Card(
    18,
    'Etienne Elion',
    'Etienne',
    'Elion',
    'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    'https://picsum.photos/200',
    'Ms',
    true,
  ),
  new Card(
    19,
    "Clemmy O'Noland",
    'Clemmy',
    "O'Noland",
    'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    'https://picsum.photos/200',
    'Mr',
    false,
  ),
  new Card(
    20,
    'Krissy Napton',
    'Krissy',
    'Napton',
    'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    'https://picsum.photos/200',
    'Mrs',
    false,
  ),
];
